import { cyan, dim, gray, green } from "kleur/colors";

export function parseEnvContent(content: string): Record<string, string> {
  const result: Record<string, string> = {};

  for (const line of content.split("\n")) {
    const trimmed = line.trim();

    // Skip empty lines and comments
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }

    const equalIndex = trimmed.indexOf("=");
    if (equalIndex === -1) {
      continue;
    }

    const key = trimmed.slice(0, equalIndex).trim();
    let value = trimmed.slice(equalIndex + 1).trim();

    // Check if value is quoted
    const isQuoted =
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"));

    // Remove surrounding quotes if present
    if (isQuoted) {
      value = value.slice(1, -1);
    } else {
      // Remove inline comment for unquoted values
      const commentIndex = value.indexOf("#");
      if (commentIndex !== -1) {
        value = value.slice(0, commentIndex).trim();
      }
    }

    if (key) {
      result[key] = value;
    }
  }

  return result;
}

/**
 * Converts JSON object to .env format string.
 */
export function jsonToEnv(data: Record<string, string>): string {
  return Object.entries(data)
    .map(([key, value]) => {
      const escaped = value.replace(/"/g, '\\"');
      return `${key}="${escaped}"`;
    })
    .join("\n");
}

export function generateEnvHeader(secretName: string): string {
  return `# Generated by e2sm\n# Source: ${secretName}`;
}

export function formatJson(obj: unknown, indent = 0): string {
  const spaces = "  ".repeat(indent);

  if (obj === null) {
    return gray("null");
  }

  if (typeof obj === "string") {
    return green(`"${obj}"`);
  }

  if (typeof obj === "number" || typeof obj === "boolean" || typeof obj === "bigint") {
    return String(obj);
  }

  if (typeof obj === "undefined") {
    return gray("undefined");
  }

  if (typeof obj === "symbol") {
    return gray(obj.toString());
  }

  if (typeof obj === "function") {
    return gray("[Function]");
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) return dim("[]");
    const items = obj.map((item) => `${spaces}  ${formatJson(item, indent + 1)}`);
    return `${dim("[")}\n${items.join(`${dim(",")}\n`)}\n${spaces}${dim("]")}`;
  }

  // obj is now narrowed to object (non-null, non-array)
  const entries = Object.entries(obj);
  if (entries.length === 0) return dim("{}");
  const items = entries.map(
    ([key, value]) => `${spaces}  ${cyan(`"${key}"`)}${dim(":")} ${formatJson(value, indent + 1)}`,
  );
  return `${dim("{")}\n${items.join(`${dim(",")}\n`)}\n${spaces}${dim("}")}`;
}
